repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

{% if cookiecutter.use_black == 'y' %}
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
{% endif %}
