repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

{% if cookiecutter.use_black == 'y' %}
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        name: Format code with black
{% endif %}

  - repo: https://github.com/jazzband/pip-tools
    rev: 5.1.2
    hooks:
      - id: pip-compile
        name: Generate requirements.txt
        files: ^(setup\.py|requirements\.txt)$
      - id: pip-compile
        name: Generate requirements_dev.txt
        files: ^requirements_dev\.(in|txt)$
        args: [ requirements_dev.in ]

{% if cookiecutter.use_isort == 'y' %}
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
{% endif %}
